import React, { useState, useEffect } from "react";
import { 
  Cpu, 
  Mail, 
  FileText, 
  Play, 
  Trash2, 
  Clock, 
  Inbox, 
  RefreshCw, 
  ToggleLeft, 
  ToggleRight
} from "lucide-react";
import { 
  getWorkflows, 
  updateWorkflowStatus, 
  getLogs, 
  clearLogs, 
  getSentEmails, 
  clearSentEmails,
  triggerExpiryCheck 
} from "../services/automation";

export default function AutomationWorkflow({ medicines, currentUser, onShowToast }) {
  const [activeTab, setActiveTab] = useState("workflows"); // workflows | logs | outbox
  const [workflowsList, setWorkflowsList] = useState([]);
  const [executionLogs, setExecutionLogs] = useState([]);
  const [sentMails, setSentMails] = useState([]);
  const [selectedMail, setSelectedMail] = useState(null);
  
  // Expiry Run Action Status States
  const [isRunningScan, setIsRunningScan] = useState(false);
  const [logSearch, setLogSearch] = useState("");

  useEffect(() => {
    loadAutomationData();
    const handleMailRefresh = () => loadAutomationData();
    window.addEventListener("medicycle_mail_refresh", handleMailRefresh);
    // eslint-disable-next-line react-hooks/exhaustive-deps
    return () => window.removeEventListener("medicycle_mail_refresh", handleMailRefresh);
  }, []);

  const loadAutomationData = () => {
    setWorkflowsList(getWorkflows());
    setExecutionLogs(getLogs());
    const emails = getSentEmails();
    setSentMails(emails);
    if (emails.length > 0 && !selectedMail) {
      setSelectedMail(emails[0]);
    }
  };

  const handleToggleWorkflow = (id, currentStatus) => {
    const updated = updateWorkflowStatus(id, !currentStatus);
    if (updated) {
      onShowToast(`Workflow "${updated.name}" is now ${updated.isActive ? "active" : "inactive"}.`, "info");
      loadAutomationData();
    }
  };

  const handleRunExpiryCheck = async () => {
    setIsRunningScan(true);
    // Simulate API delay
    setTimeout(async () => {
      try {
        const result = await triggerExpiryCheck(medicines, currentUser.email);
        setIsRunningScan(false);
        loadAutomationData();
        
        if (result.status === "run") {
          onShowToast(result.message, "success");
        } else if (result.status === "secure") {
          onShowToast("Scan complete. Cabinet is secure, no expiring packages found.", "success");
        } else {
          onShowToast("Scan skipped: Expiry Warn Workflow is inactive.", "error");
        }
      } catch (err) {
        console.error(err);
        setIsRunningScan(false);
        onShowToast("API expiry check process failure.", "error");
      }
    }, 1000);
  };

  const handleClearLogs = () => {
    if (window.confirm("Verify clear all workflow execution logs?")) {
      clearLogs();
      onShowToast("Automation logs cleared.", "info");
      loadAutomationData();
    }
  };

  const handleClearMails = () => {
    if (window.confirm("Verify clear all simulated outbox items?")) {
      clearSentEmails();
      setSelectedMail(null);
      onShowToast("Simulated sent inbox cleared.", "info");
      loadAutomationData();
    }
  };

  // Filter logs based on search string
  const filteredLogs = executionLogs.filter(log => 
    log.details.toLowerCase().includes(logSearch.toLowerCase()) || 
    log.workflowId.toLowerCase().includes(logSearch.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-slideUp">
      
      {/* Title Header area */}
      <div className="bg-gradient-to-r from-primary to-primary-accent p-6 sm:p-8 rounded-lg shadow-sm text-white space-y-3">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center text-white">
            <Cpu className="w-6 h-6" />
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight">
            Automation <span className="text-primary-light">Workflows</span>
          </h1>
        </div>
        <p className="text-primary-light max-w-2xl text-sm sm:text-base leading-relaxed">
          Configure rule triggers, track daemon schedulers, and monitor the transactional email output queue generated by Medicycle AI workflows.
        </p>
      </div>

      {/* Tabs Switcher Control Panel */}
      <div className="border-b border-gray-200 bg-white p-2 rounded-t-lg shadow-sm border border-gray-100 flex flex-wrap gap-2">
        <button
          onClick={() => setActiveTab("workflows")}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-md text-sm font-bold transition-all ${
            activeTab === "workflows" 
              ? "bg-primary text-white shadow-sm" 
              : "text-text-muted hover:bg-primary-light hover:text-primary"
          }`}
        >
          <Cpu className="w-4 h-4" />
          Active Workflows ({workflowsList.length})
        </button>
        <button
          onClick={() => setActiveTab("logs")}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-md text-sm font-bold transition-all ${
            activeTab === "logs" 
              ? "bg-primary text-white shadow-sm" 
              : "text-text-muted hover:bg-primary-light hover:text-primary"
          }`}
        >
          <FileText className="w-4 h-4" />
          Execution Logs ({executionLogs.length})
        </button>
        <button
          onClick={() => setActiveTab("outbox")}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-md text-sm font-bold transition-all ${
            activeTab === "outbox" 
              ? "bg-primary text-white shadow-sm" 
              : "text-text-muted hover:bg-primary-light hover:text-primary"
          }`}
        >
          <Mail className="w-4 h-4" />
          Simulated Sent Mail ({sentMails.length})
        </button>
      </div>

      {/* VIEW PANEL 1: WORKFLOWS */}
      {activeTab === "workflows" && (
        <div className="space-y-6">
          
          {/* Quick Scheduler Sync Button */}
          <div className="bg-emerald-50 border border-emerald-100 p-5 rounded-lg flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex gap-3">
              <Clock className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="font-extrabold text-emerald-900 text-sm">Scheduler Daemon Control</h4>
                <p className="text-xs text-emerald-800 leading-relaxed mt-0.5">
                  Daily schedulers scan active shelves to trigger the Expiry Warning workflow. Trigger a manual sync run below.
                </p>
              </div>
            </div>
            <button
              onClick={handleRunExpiryCheck}
              disabled={isRunningScan}
              className="flex items-center justify-center gap-2 px-4 py-2 bg-primary hover:bg-primary-hover text-white text-xs font-black uppercase tracking-wider rounded shadow transition-all duration-200 disabled:opacity-50"
            >
              {isRunningScan ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  Running Sync...
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5" />
                  Run Expiry Check Daemon
                </>
              )}
            </button>
          </div>

          {/* Workflow Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {workflowsList.map((wf) => (
              <div 
                key={wf.id}
                className={`bg-white rounded-lg shadow-sm border border-gray-100 p-5 flex flex-col justify-between space-y-4 hover:shadow-md transition-all duration-300 ${
                  !wf.isActive ? "bg-gray-50/50 opacity-75" : ""
                }`}
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-primary bg-primary-light border border-primary/20 px-2 py-0.5 rounded-full">
                      API Trigger
                    </span>
                    <button
                      onClick={() => handleToggleWorkflow(wf.id, wf.isActive)}
                      className="text-text-muted hover:text-text-main transition-color"
                      title={wf.isActive ? "Deactivate Workflow" : "Activate Workflow"}
                    >
                      {wf.isActive ? (
                        <ToggleRight className="w-9 h-9 text-primary cursor-pointer" />
                      ) : (
                        <ToggleLeft className="w-9 h-9 text-text-muted cursor-pointer" />
                      )}
                    </button>
                  </div>
                  
                  <h3 className="font-extrabold text-base text-text-main leading-snug">
                    {wf.name}
                  </h3>
                  
                  <p className="text-xs text-text-muted leading-relaxed">
                    {wf.description}
                  </p>
                </div>

                <div className="pt-4 border-t border-gray-50 text-[11px] space-y-1.5 text-text-muted bg-gray-50/50 -mx-5 -mb-5 p-4 rounded-b-lg">
                  <div><span className="font-bold text-text-main">Event:</span> {wf.trigger}</div>
                  <div><span className="font-bold text-text-main">Rule:</span> {wf.condition}</div>
                  <div><span className="font-bold text-text-main">Action:</span> {
                    wf.actionType === "both" ? "SMTP Email Reminder & Alert Notification" :
                    wf.actionType === "email" ? "SMTP Transactional Email Alert" : "Dashboard Alert Notification"
                  }</div>
                </div>
              </div>
            ))}
          </div>

        </div>
      )}

      {/* VIEW PANEL 2: EXECUTION LOGS */}
      {activeTab === "logs" && (
        <div className="bg-white rounded-lg border border-gray-150 shadow-sm overflow-hidden p-6 space-y-4">
          
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-gray-100 pb-4">
            <div>
              <h3 className="text-lg font-bold text-text-main">Active Engine Triggers Logs</h3>
              <p className="text-xs text-text-muted">A list of all executions, runs, and trigger evaluations.</p>
            </div>
            <div className="flex items-center gap-3">
              <input
                type="text"
                placeholder="Filter logs by details..."
                value={logSearch}
                onChange={(e) => setLogSearch(e.target.value)}
                className="px-3 py-1.5 text-xs rounded border border-gray-200 focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary"
              />
              <button
                onClick={handleClearLogs}
                disabled={executionLogs.length === 0}
                className="flex items-center gap-1 px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-600 rounded text-xs font-bold transition-all disabled:opacity-40"
              >
                <Trash2 className="w-3.5 h-3.5" />
                Clear Logs
              </button>
            </div>
          </div>

          {filteredLogs.length === 0 ? (
            <div className="py-16 text-center text-text-muted space-y-3">
              <FileText className="w-12 h-12 text-gray-200 mx-auto" />
              <p className="font-semibold text-sm">No workflow execution logs found</p>
              <p className="text-xs max-w-xs mx-auto">Either execute the Expiry scan or trigger adding/donating medicines. Logs will appear here.</p>
            </div>
          ) : (
            <div className="overflow-x-auto max-h-[460px] overflow-y-auto border border-gray-100 rounded">
              <table className="w-full text-left text-xs border-collapse">
                <thead className="bg-gray-50 border-b border-gray-150 text-text-main font-bold sticky top-0">
                  <tr>
                    <th className="p-3">Timestamp</th>
                    <th className="p-3">Rule/ID</th>
                    <th className="p-3">Details</th>
                    <th className="p-3">Evaluation Code</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 font-medium">
                  {filteredLogs.map((log) => (
                    <tr key={log.id} className="hover:bg-gray-50/50">
                      <td className="p-3 text-text-muted whitespace-nowrap">
                        {new Date(log.timestamp).toLocaleString()}
                      </td>
                      <td className="p-3 text-text-main font-bold">
                        <span className="bg-gray-100 border border-gray-150 px-2 py-0.5 rounded text-[10px]">
                          {log.workflowId}
                        </span>
                      </td>
                      <td className="p-3 text-text-main">
                        {log.details}
                      </td>
                      <td className="p-3">
                        <span className={`px-2.5 py-0.5 text-[10px] font-bold rounded-full border ${
                          log.status === "success" 
                            ? "bg-green-50 text-green-700 border-green-200" 
                            : log.status === "skipped"
                            ? "bg-orange-50 text-orange-700 border-orange-200"
                            : "bg-red-50 text-red-700 border-red-200"
                        }`}>
                          {log.status.toUpperCase()}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* VIEW PANEL 3: SIMULATED SENT MAILS */}
      {activeTab === "outbox" && (
        <div className="bg-white rounded-lg border border-gray-150 shadow-sm overflow-hidden p-6 space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-100 pb-4">
            <div>
              <h3 className="text-lg font-bold text-text-main">Simulated SMTP Sent Envelope Queue</h3>
              <p className="text-xs text-text-muted">Direct transactional SMTP sandbox pipeline output rendering visual HTML mail logs.</p>
            </div>
            <button
              onClick={handleClearMails}
              disabled={sentMails.length === 0}
              className="flex items-center justify-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-600 rounded text-xs font-bold transition-all disabled:opacity-40"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Clear Mail Log
            </button>
          </div>

          {sentMails.length === 0 ? (
            <div className="py-16 text-center text-text-muted space-y-3">
              <Inbox className="w-12 h-12 text-gray-200 mx-auto" />
              <p className="font-semibold text-sm">Simulated mailboxes are empty</p>
              <p className="text-xs max-w-xs mx-auto">Launch the Expiry scanning daemon, mark a medicine as Donate, or add new batches to monitor outgoing SMTP mail deliveries.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-12 border border-gray-150 rounded overflow-hidden divide-y lg:divide-y-0 lg:divide-x divide-gray-150 h-[500px]">
              
              {/* Mail list sidebar (5 cols) */}
              <div className="lg:col-span-5 overflow-y-auto divide-y divide-gray-100 bg-gray-50/30">
                {sentMails.map((mail) => (
                  <div
                    key={mail.id}
                    onClick={() => setSelectedMail(mail)}
                    className={`p-4 cursor-pointer hover:bg-emerald-50/30 transition-all text-left space-y-1.5 ${
                      selectedMail?.id === mail.id 
                        ? "bg-primary-light border-l-4 border-primary" 
                        : ""
                    }`}
                  >
                    <div className="flex items-center justify-between gap-4">
                      <span className="text-[10px] font-bold text-primary font-mono truncate">
                        TO: {mail.recipient}
                      </span>
                      <span className="text-[9px] text-text-muted whitespace-nowrap">
                        {new Date(mail.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                    <h4 className="text-xs font-black text-text-main line-clamp-1 leading-snug">
                      {mail.subject}
                    </h4>
                    <p className="text-[11px] text-text-muted line-clamp-1">
                      SMTP pipeline secure processing complete. Click to render.
                    </p>
                  </div>
                ))}
              </div>
              
              {/* Mail body viewer (7 cols) */}
              <div className="lg:col-span-7 flex flex-col bg-white overflow-hidden">
                {selectedMail ? (
                  <div className="h-full flex flex-col overflow-hidden">
                    {/* Header */}
                    <div className="p-4 bg-gray-50/50 border-b border-gray-100 text-left text-xs space-y-1 flex-shrink-0">
                      <div>
                        <span className="font-bold text-text-muted">From:</span>{" "}
                        <span className="font-semibold text-primary">MediCycle AI Engine &lt;noreply@medicycle.ai&gt;</span>
                      </div>
                      <div>
                        <span className="font-bold text-text-muted">To:</span>{" "}
                        <span className="font-semibold text-text-main">{selectedMail.recipient}</span>
                      </div>
                      <div>
                        <span className="font-bold text-text-muted">Subject:</span>{" "}
                        <span className="font-semibold text-text-main">{selectedMail.subject}</span>
                      </div>
                      <div className="text-[10px] text-text-muted">
                        <span className="font-bold">Sent:</span> {new Date(selectedMail.timestamp).toLocaleString()}
                      </div>
                    </div>
                    
                    {/* HTML Content render */}
                    <div className="flex-1 p-6 overflow-y-auto bg-gray-50/50 flex justify-center">
                      <div 
                        className="w-full max-w-full overflow-x-auto bg-white border border-gray-150 rounded"
                        dangerouslySetInnerHTML={{ __html: selectedMail.body }}
                      />
                    </div>
                  </div>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-center text-text-muted space-y-2 p-8">
                    <Mail className="w-12 h-12 text-gray-200" />
                    <p className="font-semibold text-sm">Select an email to render content</p>
                  </div>
                )}
              </div>

            </div>
          )}
        </div>
      )}

    </div>
  );
}
